### ISSUE TITLE
OSError thrown upon starting the example

### ISSUE THREAD

**Issue by blackplague** [neo4j-examples/movies-python-bolt#8]
I have exported the NEO4J_PASSWORD environment variable, even tried replacing the password in the driver initialization. Also tried adding a port number in the driver line.

`(neo4j-movies)#> python movies.py
Traceback (most recent call last):
  File "movies.py", line 13, in <module>
    driver = GraphDatabase.driver('bolt://localhost',auth=basic_auth("neo4j", password))
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/v1/api.py", line 94, in driver
    return Driver(uri, **config)
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/v1/api.py", line 133, in __new__
    return subclass(uri, **config)
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/v1/direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/v1/direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 453, in acquire_direct
    connection = self.connector(address, self.connection_error_handler)
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/v1/direct.py", line 70, in connector
    return connect(address, security_plan.ssl_context, error_handler, **config)
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 707, in connect
    raise last_error
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 698, in connect
    s, der_encoded_server_certificate = _secure(s, address[0], ssl_context, **config)
  File "/home/blackplague/development/movies-python-bolt/neo4j-movies/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 601, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/home/blackplague/bin/anaconda3/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/home/blackplague/bin/anaconda3/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/home/blackplague/bin/anaconda3/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error`

Any idea how to progress from here?

**Comment by blackplague** [comment]
I found the answer myself. It seems to be an upstream bug from: https://bugs.python.org/issue31122

So not much that can be done currently. I'm closing it again.

**Comment by gopalpeddinti** [comment]
Hi, I am having the same issue here with Python 3.6.9 (on Ubuntu 18.04LTS), and hence I can't run the app. Is this now a dead-end, I won't just be able to use this?

**Comment by geofflangenderfer** [comment]
I have this issue with:
- Ubuntu 20.04
- Python 3.8.2
